#FROM mysql:8.0
#ENV LANG ja_JP.UTF-8

FROM centos:8
#RUN dnf -y update

# install server & client
#RUN dnf install -y @mysql

#COPY my.cnf /etc/my.cnf

###ENV MYSQL_DATABASE=voices
#ENV MYSQL_USER=admin
#ENV MYSQL_PASSWORD=admin
#ENV MYSQL_ROOT_PASSWORD=admin
#ENV MYSQL_HOST=mysql
#ENV MYSQL_PORT=3306

#EXPOSE 3306